import { Router, type IRouter, type Request, type Response } from "express";
import { db, projectsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const router: IRouter = Router();

// ── Heuristic Design.md generator ────────────────────────────────────
interface DesignProfile {
  background: string;
  foreground: string;
  primary: string;
  secondary: string;
  muted: string;
  accent: string;
  border: string;
  font: string;
  headingFont: string;
  fontSize: string;
  radius: string;
  style: string;
  personality: string;
  tone: string;
}

function detectProfile(prompt: string): DesignProfile {
  const p = (prompt ?? "").toLowerCase();

  const isDark   = /dark|night|black|noir|deep/.test(p);
  const isLight  = /light|white|clean|bright|airy/.test(p);
  const isBold   = /bold|strong|impact|dramatic|powerful/.test(p);
  const isMinimal= /minimal|simple|clean|bare|stripped/.test(p);
  const isPlayful= /playful|fun|creative|colorful|vibrant|bubbly/.test(p);
  const isCorp   = /corporate|professional|business|enterprise|formal/.test(p);
  const isElegant= /elegant|luxury|premium|sophisticated|upscale|fashion/.test(p);
  const isTech   = /tech|startup|saas|app|software|developer|code|ai/.test(p);
  const isNature = /nature|eco|green|organic|botanical|earth|outdoor/.test(p);
  const isRetro  = /retro|vintage|classic|nostalgic|80s|90s/.test(p);

  // Accent color detection
  let primary = "#6366F1";
  if (/blue|ocean|sky|navy/.test(p))     primary = "#3B82F6";
  if (/purple|violet|indigo/.test(p))    primary = "#8B5CF6";
  if (/green|emerald|mint|sage/.test(p)) primary = "#10B981";
  if (/red|crimson|ruby/.test(p))        primary = "#EF4444";
  if (/orange|amber|warm|fire/.test(p))  primary = "#F97316";
  if (/pink|rose|blush/.test(p))         primary = "#EC4899";
  if (/gold|yellow|sunny/.test(p))       primary = "#F59E0B";
  if (/teal|cyan|aqua/.test(p))          primary = "#06B6D4";
  if (isNature)                           primary = "#16A34A";
  if (isRetro)                            primary = "#F59E0B";

  const bg  = isDark ? "#0A0A0A" : isLight ? "#FAFAFA" : isCorp ? "#F8FAFC" : isNature ? "#F0FDF4" : "#FFFFFF";
  const fg  = isDark ? "#FFFFFF" : "#0F172A";
  const border = isDark ? "#1E293B" : "#E2E8F0";
  const muted  = isDark ? "#64748B" : "#94A3B8";

  // Derive secondary/accent from primary
  const secondary = isDark ? primary.replace(/#/, "#") : primary + "99";

  let font = "Inter, sans-serif";
  if (isElegant || /serif/.test(p)) font = "Playfair Display, serif";
  if (isTech)                       font = "JetBrains Mono, monospace";
  if (isPlayful)                    font = "DM Sans, sans-serif";
  if (isCorp)                       font = "DM Sans, sans-serif";
  if (isNature)                     font = "Lato, sans-serif";

  let headingFont = font;
  if (isElegant) headingFont = "Playfair Display, serif";

  let radius = "0.75rem";
  if (isMinimal || isElegant || isCorp) radius = "0.375rem";
  if (isPlayful)                        radius = "1.5rem";
  if (isBold)                           radius = "0.5rem";

  let style = "Balanced, professional";
  if (isDark && isMinimal) style = "Dark, minimal";
  else if (isDark && isTech) style = "Dark, tech-forward";
  else if (isLight && isMinimal) style = "Light, minimal";
  else if (isElegant) style = "Elegant, refined";
  else if (isPlayful) style = "Playful, vibrant";
  else if (isCorp) style = "Corporate, clean";
  else if (isNature) style = "Organic, natural";
  else if (isRetro) style = "Retro, vintage";
  else if (isDark) style = "Dark, dramatic";

  let personality = "Trustworthy and innovative";
  if (isPlayful) personality = "Fun, energetic, and approachable";
  if (isElegant) personality = "Sophisticated, premium, and refined";
  if (isTech) personality = "Forward-thinking, precise, and capable";
  if (isNature) personality = "Organic, calm, and authentic";
  if (isCorp) personality = "Professional, reliable, and authoritative";

  let tone = "Confident and direct";
  if (isPlayful) tone = "Warm, friendly, and conversational";
  if (isElegant) tone = "Understated, polished, and aspirational";
  if (isTech) tone = "Technical, precise, and results-focused";

  return {
    background: bg, foreground: fg, primary,
    secondary: isDark ? "#8B5CF6" : "#A5B4FC",
    muted, accent: isDark ? "#06B6D4" : "#0EA5E9", border,
    font, headingFont, fontSize: "16px", radius,
    style, personality, tone,
  };
}

function buildDesignMd(profile: DesignProfile, projectName: string, source: string): string {
  return `# Design System — ${projectName}

> Generated by WWW Studio AI · Source: ${source}

## Brand Identity
- **Style**: ${profile.style}
- **Personality**: ${profile.personality}
- **Tone**: ${profile.tone}

---

## Color Palette

| Token | Value | Usage |
|-------|-------|-------|
| Background | \`${profile.background}\` | Page background |
| Foreground | \`${profile.foreground}\` | Primary text |
| Primary | \`${profile.primary}\` | CTAs, links, highlights |
| Secondary | \`${profile.secondary}\` | Hover states, gradients |
| Muted | \`${profile.muted}\` | Secondary text, placeholders |
| Accent | \`${profile.accent}\` | Badges, special highlights |
| Border | \`${profile.border}\` | Dividers, card outlines |

---

## Typography

- **Body Font**: ${profile.font}
- **Heading Font**: ${profile.headingFont}
- **Base Size**: ${profile.fontSize}
- **Scale Ratio**: 1.25 (Major Third)

### Type Scale
| Style | Size | Weight | Usage |
|-------|------|--------|-------|
| Display | 3.052rem | 800 | Hero headlines |
| H1 | 2.441rem | 700 | Page titles |
| H2 | 1.953rem | 600 | Section headers |
| H3 | 1.563rem | 600 | Subsections |
| Body | 1rem | 400 | Body text |
| Small | 0.8rem | 400 | Captions, labels |

---

## Spacing System

Base unit: **4px**

| Token | Value | Usage |
|-------|-------|-------|
| xs | 4px | Icon gaps |
| sm | 8px | Tight spacing |
| md | 16px | Default padding |
| lg | 24px | Section padding |
| xl | 48px | Large gaps |
| 2xl | 64px | Section margins |
| 3xl | 96px | Hero padding |

---

## Border & Effects

- **Radius (buttons)**: ${profile.radius}
- **Radius (cards)**: calc(${profile.radius} + 0.25rem)
- **Subtle shadow**: \`0 1px 3px rgba(0,0,0,0.12)\`
- **Card shadow**: \`0 4px 16px rgba(0,0,0,0.15)\`
- **Elevated shadow**: \`0 8px 32px rgba(0,0,0,0.20)\`

---

## Component Patterns

### Buttons
\`\`\`
Primary: bg-primary text-white font-medium rounded-[${profile.radius}] px-5 py-2.5 hover:opacity-90 transition-opacity
Secondary: border border-primary/30 text-primary rounded-[${profile.radius}] px-5 py-2.5 hover:bg-primary/10
Ghost: text-muted-foreground hover:text-foreground px-4 py-2 rounded
\`\`\`

### Cards
\`\`\`
Base: bg-card border border-border/50 rounded-xl p-6 transition-colors hover:border-primary/30
Featured: bg-primary/5 border border-primary/20 rounded-xl p-6
\`\`\`

### Inputs
\`\`\`
bg-background border border-border rounded-[${profile.radius}] px-4 py-2.5 text-sm
focus:border-primary/50 focus:ring-2 focus:ring-primary/10 focus:outline-none
\`\`\`

---

## Design Tokens (JSON)

\`\`\`json
${JSON.stringify({
  colors: {
    background: profile.background,
    foreground: profile.foreground,
    primary: profile.primary,
    secondary: profile.secondary,
    muted: profile.muted,
    accent: profile.accent,
    border: profile.border,
  },
  fonts: {
    body: profile.font,
    heading: profile.headingFont,
    fontSize: profile.fontSize,
  },
  radius: profile.radius,
  style: profile.style,
}, null, 2)}
\`\`\`
`;
}

// ── Try OpenAI if key is set ──────────────────────────────────────────
async function generateWithOpenAI(prompt: string, projectName: string): Promise<string | null> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;

  try {
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are a world-class design systems expert. Generate a comprehensive Design.md file for a web project.

Output a Markdown document with these sections:
1. Brand Identity (style, personality, tone)
2. Color Palette (7 tokens as a table: background, foreground, primary, secondary, muted, accent, border — with hex values)
3. Typography (font family, scale)
4. Spacing System
5. Component Patterns (button, card, input Tailwind classes)
6. Design Tokens JSON block (MUST include — parseable JSON with colors, fonts, radius, style keys)

The Design Tokens JSON block must follow this exact format:
\`\`\`json
{
  "colors": { "background": "#...", "foreground": "#...", "primary": "#...", "secondary": "#...", "muted": "#...", "accent": "#...", "border": "#..." },
  "fonts": { "body": "...", "heading": "...", "fontSize": "16px" },
  "radius": "0.75rem",
  "style": "..."
}
\`\`\`

Make the design system cohesive, professional, and directly applicable with Tailwind CSS.`,
        },
        {
          role: "user",
          content: `Create a Design.md for project "${projectName}" with this design direction:\n\n${prompt}`,
        },
      ],
      max_tokens: 2000,
    });

    return completion.choices[0]?.message?.content ?? null;
  } catch {
    return null;
  }
}

// ── Routes ─────────────────────────────────────────────────────────────

// Generate Design.md
router.post("/projects/:id/design-md", async (req: Request, res: Response) => {
  const projectId = String(req.params.id);
  const { prompt = "", url = "", mode = "prompt" } = req.body;

  const project = await db.query.projectsTable.findFirst({
    where: eq(projectsTable.id, projectId),
  });

  if (!project) { res.status(404).json({ error: "Project not found" }); return; }

  const projectName = project.name ?? "My Project";
  const source = mode === "url" ? url || "URL" : mode === "images" ? "uploaded images" : "prompt";
  const userPrompt = url ? `Inspired by website: ${url}\n\nAdditional notes: ${prompt}` : prompt || "modern, clean, professional web design";

  // Try OpenAI first, fall back to heuristics
  let designMd = await generateWithOpenAI(userPrompt, projectName);

  if (!designMd) {
    const profile = detectProfile(userPrompt);
    designMd = buildDesignMd(profile, projectName, source);
  }

  // Store in themeTokens
  let tokens: Record<string, unknown> = {};
  try { tokens = JSON.parse(project.themeTokens ?? "{}"); } catch { /* */ }
  const updatedTokens = JSON.stringify({ ...tokens, designMd });

  await db.update(projectsTable).set({ themeTokens: updatedTokens }).where(eq(projectsTable.id, projectId));

  res.json({ designMd });
});

// Get stored Design.md
router.get("/projects/:id/design-md", async (req: Request, res: Response) => {
  const project = await db.query.projectsTable.findFirst({
    where: eq(projectsTable.id, String(req.params.id)),
  });
  if (!project) { res.status(404).json({ error: "Project not found" }); return; }

  let designMd: string | null = null;
  try {
    const tokens = JSON.parse(project.themeTokens ?? "{}");
    designMd = tokens.designMd ?? null;
  } catch { /* */ }

  res.json({ designMd });
});

// Apply Design.md tokens to project theme
router.post("/projects/:id/design-md/apply", async (req: Request, res: Response) => {
  const projectId = String(req.params.id);
  const { tokens: designTokens } = req.body;

  if (!designTokens?.colors) { res.status(400).json({ error: "Invalid design tokens" }); return; }

  const project = await db.query.projectsTable.findFirst({
    where: eq(projectsTable.id, projectId),
  });
  if (!project) { res.status(404).json({ error: "Project not found" }); return; }

  let existingTokens: Record<string, unknown> = {};
  try { existingTokens = JSON.parse(project.themeTokens ?? "{}"); } catch { /* */ }

  // Map Design.md color tokens to themeTokens format used by ThemeCustomizer
  const colorMap = designTokens.colors ?? {};
  const merged = {
    ...existingTokens,
    background: colorMap.background ?? existingTokens.background,
    foreground: colorMap.foreground ?? existingTokens.foreground,
    primary: colorMap.primary ?? existingTokens.primary,
    secondary: colorMap.secondary ?? existingTokens.secondary,
    muted: colorMap.muted ?? existingTokens.muted,
    accent: colorMap.accent ?? existingTokens.accent,
    border: colorMap.border ?? existingTokens.border,
    fontFamily: designTokens.fonts?.body ?? existingTokens.fontFamily,
    baseFontSize: designTokens.fonts?.fontSize ?? existingTokens.baseFontSize,
    borderRadius: designTokens.radius ?? existingTokens.borderRadius,
  };

  const newTokens = JSON.stringify(merged);
  await db.update(projectsTable).set({ themeTokens: newTokens }).where(eq(projectsTable.id, projectId));

  res.json({ themeTokens: newTokens });
});

export default router;
